# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'act2.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtWidgets import QApplication, QWidget, QPushButton
from PyQt5.QtCore import pyqtSlot

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow, QApplication, QWidget, QPushButton, QAction, QLineEdit, QMessageBox

from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *

import time

import main





class Ui_WebActuary(object):
    def setupUi(self, WebActuary):
        WebActuary.setObjectName("WebActuary")
        WebActuary.resize(627, 333)
        WebActuary.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        WebActuary.setAutoFillBackground(True)

        self.label = QtWidgets.QLabel(WebActuary)
        self.label.setGeometry(QtCore.QRect(130, 100, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)

        # input field for url
        self.label.setObjectName("label")
        self.textBox = QtWidgets.QLineEdit(WebActuary)
        self.textBox.setGeometry(QtCore.QRect(240, 100, 251, 31))
        self.textBox.setText("")
        self.textBox.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(WebActuary)
        self.label_2.setGeometry(QtCore.QRect(240, 20, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        # AUDIT button
        self.pushButton = QtWidgets.QPushButton(WebActuary)
        self.pushButton.setGeometry(QtCore.QRect(250, 170, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.line = QtWidgets.QFrame(WebActuary)
        self.line.setGeometry(QtCore.QRect(30, 230, 571, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)

        # line object(graphic)
        self.line.setObjectName("line")

        # progrss bar
        self.progressBar = QtWidgets.QProgressBar(WebActuary)
        self.progressBar.setGeometry(QtCore.QRect(200, 270, 271, 31))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.label_3 = QtWidgets.QLabel(WebActuary)
        self.label_3.setGeometry(QtCore.QRect(260, 270, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(WebActuary)
        QtCore.QMetaObject.connectSlotsByName(WebActuary)


        self.pushButton.clicked.connect(self.on_click)
        #self.show()

    def retranslateUi(self, WebActuary):
        _translate = QtCore.QCoreApplication.translate
        WebActuary.setWindowTitle(_translate("WebActuary", "Auditor"))
        self.label.setText(_translate("WebActuary", "Enter URL : "))
        self.label_2.setText(_translate("WebActuary", "WebActuary"))
        self.pushButton.setText(_translate("WebActuary", "AUDIT"))
        self.label_3.setText(_translate("WebActuary", "Auditing URL..."))


    def on_click(self):
        # progressbar
        for i in range(95):
            # slowing down the loop
            time.sleep(0.05)

            # setting value to progress bar
            self.progressBar.setValue(i)

        # extracting text from input field
        url = self.textBox.text()
        print(url)
        main.run_program(url)
        """self.worker.moveToThread(self.thread)
        self.thread.started.connect(self.worker.run_program(url))
        self.thread.start"""
        print("ok")

        '''main code runs here'''

        for i in range(95,101):
            # slowing down the loop
            time.sleep(0.05)

            # setting value to progress bar
            self.progressBar.setValue(i)

        #messgae box
        msg = QMessageBox()
        msg.setIcon(QMessageBox.Information)

        msg.setText("Report generated successfully!!!")
        msg.setInformativeText("You can find the report at <path>")
        msg.setWindowTitle("WebActuary Auditor")
        msg.setDetailedText("Details are as follows:")
        msg.setStandardButtons(QMessageBox.Ok | QMessageBox.Cancel)

        retval = msg.exec_()




if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    WebActuary = QtWidgets.QDialog()
    ui = Ui_WebActuary()
    ui.setupUi(WebActuary)
    WebActuary.show()
    sys.exit(app.exec_())
